# Nombre de la aplicación
spring.application.name=coworking

# Configuración de la Base de Datos H2
spring.datasource.url=jdbc:h2:mem:coworkingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola H2 (Para que puedas ver las tablas en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate / JPA
# 'update' crea las tablas automáticamente basadas en tus clases @Entity
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 1. Obliga a Spring a esperar que Hibernate cree las tablas antes de ejecutar el SQL
spring.jpa.defer-datasource-initialization=true

# 2. Asegura que el modo de inicialización esté activo
spring.sql.init.mode=always